# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amulet < Formula
  desc ""
  homepage "https://github.com/Hwansul/amulet"
  version "0.3.3"

  on_macos do
    url "https://github.com/Hwansul/amulet/releases/download/v0.3.3/amulet_0.3.3_darwin_all.tar.gz"
    sha256 "90618a855a0cd6fd68e1841336ddb2e142615d115c76c7a70b9ad7f239d31681"

    def install
      bin.install "amulet"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Hwansul/amulet/releases/download/v0.3.3/amulet_0.3.3_linux_amd64.tar.gz"
      sha256 "2c9aa18d77cff4659085504458161ebf588915fefd009e9c917d0649168b4423"

      def install
        bin.install "amulet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hwansul/amulet/releases/download/v0.3.3/amulet_0.3.3_linux_arm64.tar.gz"
      sha256 "082fb3a9085a92a7c101c7a6b75974368abe52cdf0699f322cab39d123474c83"

      def install
        bin.install "amulet"
      end
    end
  end
end
