# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class But < Formula
  desc ""
  homepage "https://github.com/hoehwa/but"
  version "0.2.1"

  on_macos do
    url "https://github.com/hoehwa/but/releases/download/v0.2.1/but_0.2.1_darwin_all.tar.gz"
    sha256 "1a6b4ab9d41af682a71e00259dabdad5c8fd6029bba8135892e6128e5391f6ba"

    def install
      bin.install "but"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/but/releases/download/v0.2.1/but_0.2.1_linux_arm64.tar.gz"
      sha256 "4e4122d25a6c817718a4010a7a05d3994612e3f04212012de4a58f5f216d714b"

      def install
        bin.install "but"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/but/releases/download/v0.2.1/but_0.2.1_linux_amd64.tar.gz"
      sha256 "6fc43bdf546ba8da28f54caadbb527c72da76b1e408a08dd6bf14f15d82ee260"

      def install
        bin.install "but"
      end
    end
  end
end
