# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class But < Formula
  desc ""
  homepage "https://github.com/hoehwa/but"
  version "0.2.4"

  on_macos do
    url "https://github.com/hoehwa/but/releases/download/v0.2.4/but_0.2.4_darwin_all.tar.gz"
    sha256 "2cf6a67e5071e789c2c298e711e2f08c98f424da5925e1332f2dc38f0b960fb5"

    def install
      bin.install "but"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/but/releases/download/v0.2.4/but_0.2.4_linux_amd64.tar.gz"
      sha256 "1c9ba7f680772de38c6370269880ad62ed87225db118ae69646863ffa2818fb8"

      def install
        bin.install "but"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/but/releases/download/v0.2.4/but_0.2.4_linux_arm64.tar.gz"
      sha256 "ee5ae07bff03d6b2dd68478964534b5f2e321ead7db99e7588c77f00f0c20e06"

      def install
        bin.install "but"
      end
    end
  end
end
