# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class But < Formula
  desc ""
  homepage "https://github.com/hoehwa/but"
  version "0.2.2"

  on_macos do
    url "https://github.com/hoehwa/but/releases/download/v0.2.2/but_0.2.2_darwin_all.tar.gz"
    sha256 "c35bde55f8d841a1ad5e2fbd593c0e9fcc1ec84c04a1acf026bce41a60a2a02d"

    def install
      bin.install "but"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/but/releases/download/v0.2.2/but_0.2.2_linux_arm64.tar.gz"
      sha256 "ab7be707f18ad56c2a5afab65b82050613ab93b9a8e78837d7b4604541609626"

      def install
        bin.install "but"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/but/releases/download/v0.2.2/but_0.2.2_linux_amd64.tar.gz"
      sha256 "0fbae72248615bdce162689a1acbf111af04be6505a694efe63e227744c1606e"

      def install
        bin.install "but"
      end
    end
  end
end
