# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Byeoru < Formula
  desc ""
  homepage "https://github.com/hoehwa/byeoru"
  version "0.1.0"

  on_macos do
    url "https://github.com/hoehwa/byeoru/releases/download/v0.1.0/byeoru_0.1.0_darwin_all.tar.gz"
    sha256 "28a561134106110e4f137b1a545294925bfdf85cd1521c83d713c96b5961efbe"

    def install
      bin.install "byeoru"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/byeoru/releases/download/v0.1.0/byeoru_0.1.0_linux_arm64.tar.gz"
      sha256 "52a9ef82a944daaf97995d4ee5166c9515da16d40238719d8d1cdad1f7560605"

      def install
        bin.install "byeoru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/byeoru/releases/download/v0.1.0/byeoru_0.1.0_linux_amd64.tar.gz"
      sha256 "fc2237113b6c529f7ab2c89eaf2f0deeace1610f9509be4b1bf8ac8ef7207541"

      def install
        bin.install "byeoru"
      end
    end
  end
end
