# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Byeoru < Formula
  desc ""
  homepage "https://github.com/hoehwa/byeoru"
  version "0.1.1"

  on_macos do
    url "https://github.com/hoehwa/byeoru/releases/download/v0.1.1/byeoru_0.1.1_darwin_all.tar.gz"
    sha256 "b4aae279190cf1883807654a34bb371399c5b70715912151b113e32bd22f45f2"

    def install
      bin.install "byeoru"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/byeoru/releases/download/v0.1.1/byeoru_0.1.1_linux_arm64.tar.gz"
      sha256 "b77a13002ccbebe7473e2a62a4a28658a1894d8f86fa1ea981331f001d50bc11"

      def install
        bin.install "byeoru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/byeoru/releases/download/v0.1.1/byeoru_0.1.1_linux_amd64.tar.gz"
      sha256 "b41dab8534d4ccff995f95b90975cf3558920da6b4d5a2802146fae9818933d8"

      def install
        bin.install "byeoru"
      end
    end
  end
end
