# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Byeoru < Formula
  desc ""
  homepage "https://github.com/hoehwa/byeoru"
  version "0.1.2"

  on_macos do
    url "https://github.com/hoehwa/byeoru/releases/download/v0.1.2/byeoru_0.1.2_darwin_all.tar.gz"
    sha256 "158e556ed9b179d6cecbe06bee978495bd50cd1491116439697b8011b7929c66"

    def install
      bin.install "byeoru"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/byeoru/releases/download/v0.1.2/byeoru_0.1.2_linux_arm64.tar.gz"
      sha256 "2d94e2e34ccabf2047654b7fe7db87a0709e378aa82685334715fcc5eef75412"

      def install
        bin.install "byeoru"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/byeoru/releases/download/v0.1.2/byeoru_0.1.2_linux_amd64.tar.gz"
      sha256 "8a9374c6e80311fc2b06294b1a460aa5e668d289d206db57a5fad71462097570"

      def install
        bin.install "byeoru"
      end
    end
  end
end
