# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cape < Formula
  desc ""
  homepage "https://github.com/jipilmuk/cape"
  version "0.1.0"

  on_macos do
    url "https://github.com/jipilmuk/cape/releases/download/v0.1.0/cape_0.1.0_darwin_all.tar.gz"
    sha256 "bd15c835f9911929312a23cd5e6bf6ff5f5b7cb3d3eff28df8ba6afc9476dabc"

    def install
      bin.install "cape"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jipilmuk/cape/releases/download/v0.1.0/cape_0.1.0_linux_arm64.tar.gz"
      sha256 "3f7f26e4ec1628fa4047c2c4c4daaa27230c1e4d0671044909989fae8a4bc46a"

      def install
        bin.install "cape"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jipilmuk/cape/releases/download/v0.1.0/cape_0.1.0_linux_amd64.tar.gz"
      sha256 "5def53bb77ae33e88d70a70e7bc74e757ee8b20ab4913f1bc08a5788bc5bb084"

      def install
        bin.install "cape"
      end
    end
  end
end
