# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chew < Formula
  desc ""
  homepage "https://github.com/Hwansul/chew"
  version "0.1.1"

  on_macos do
    url "https://github.com/Hwansul/chew/releases/download/v0.1.1/chew_0.1.1_darwin_all.tar.gz"
    sha256 "a1667fc1135ca88367eedaf6cc05088bb3f4d16ef31aeb5fbe12079c62b4f3c8"

    def install
      bin.install "chew"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Hwansul/chew/releases/download/v0.1.1/chew_0.1.1_linux_amd64.tar.gz"
      sha256 "b7e19d1c8abd246ad6137e14e10b51dce496664b3e6a076184d28c9f26ee2d4a"

      def install
        bin.install "chew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hwansul/chew/releases/download/v0.1.1/chew_0.1.1_linux_arm64.tar.gz"
      sha256 "9ffbaec406fd1f727e37005e39fa2d3665d2a6bdd9c01ee375956d57bf6f389f"

      def install
        bin.install "chew"
      end
    end
  end
end
