# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dev < Formula
  desc ""
  homepage "https://github.com/mindulle/cli-template-for-human"
  version "1.1.2"

  on_macos do
    url "https://github.com/mindulle/dev/releases/download/v1.1.2/dev_1.1.2_darwin_all.tar.gz"
    sha256 "9ff73870643eff4a35820f018a2906229f8520ef87f11526ec01c79dc21f84ce"

    def install
      bin.install "dev"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mindulle/dev/releases/download/v1.1.2/dev_1.1.2_linux_arm64.tar.gz"
      sha256 "a612c17343bd2765a54617f785ca68d8ad39c5d1487803f9e811bb5dc7a57e79"

      def install
        bin.install "dev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mindulle/dev/releases/download/v1.1.2/dev_1.1.2_linux_amd64.tar.gz"
      sha256 "1f30216a43c4f3fcea8419a1db9c408c7ab00424caa48c7153239b8cc960ef80"

      def install
        bin.install "dev"
      end
    end
  end
end
