# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jongi < Formula
  desc ""
  homepage "https://github.com/hoehwa/jongi"
  version "0.1.3"

  on_macos do
    url "https://github.com/hoehwa/jongi/releases/download/v0.1.3/jongi_0.1.3_darwin_all.tar.gz"
    sha256 "55cbba6a13945d05b0098ada94e4bdddca39fc2c383a00d6e42eb6514813cc9a"

    def install
      bin.install "jongi"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/jongi/releases/download/v0.1.3/jongi_0.1.3_linux_arm64.tar.gz"
      sha256 "90adceda9fcdff3006000abc0e89acb3a805d85b7f7dcab8809df7fabe2094e0"

      def install
        bin.install "jongi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/jongi/releases/download/v0.1.3/jongi_0.1.3_linux_amd64.tar.gz"
      sha256 "68a3d414c4fbbfe8faecad09bde57360b5aa465b73b71c0de613e50c2280a160"

      def install
        bin.install "jongi"
      end
    end
  end
end
