# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meok < Formula
  desc ""
  homepage "https://github.com/hoehwa/meok"
  version "0.4.20"

  on_macos do
    url "https://github.com/hoehwa/meok/releases/download/v0.4.20/meok_0.4.20_darwin_all.tar.gz"
    sha256 "19edc4e1ece5e902ad110c763932ad6cf9bbff3fd51a681768226e8c15c62785"

    def install
      bin.install "meok"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/meok/releases/download/v0.4.20/meok_0.4.20_linux_arm64.tar.gz"
      sha256 "514fd2abf4f178f2452440b5466965c838bf17355e521c958fc31fc062c24183"

      def install
        bin.install "meok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/meok/releases/download/v0.4.20/meok_0.4.20_linux_amd64.tar.gz"
      sha256 "b8b24c3f1ebcaf79f11e1c6f42a6a20e02febf58d770f95a29cedba83976a97c"

      def install
        bin.install "meok"
      end
    end
  end
end
