# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meok < Formula
  desc ""
  homepage "https://github.com/hoehwa/meok"
  version "0.4.19"

  on_macos do
    url "https://github.com/hoehwa/meok/releases/download/v0.4.19/meok_0.4.19_darwin_all.tar.gz"
    sha256 "51aae4cac0b4c407867be09dfc44fb04f3f899e204d8dcba84e4dda3143b9b06"

    def install
      bin.install "meok"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/meok/releases/download/v0.4.19/meok_0.4.19_linux_amd64.tar.gz"
      sha256 "f5e57e2d2451949267d4e57dac28c18bfa813f38b54ced2db54103c6178fb255"

      def install
        bin.install "meok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/meok/releases/download/v0.4.19/meok_0.4.19_linux_arm64.tar.gz"
      sha256 "4343481a284caf333a70da5ed63805b87bd818a3a5e5d2e09e8582c477655ae8"

      def install
        bin.install "meok"
      end
    end
  end
end
