# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meok < Formula
  desc ""
  homepage "https://github.com/hoehwa/meok"
  version "0.4.21"

  on_macos do
    url "https://github.com/hoehwa/meok/releases/download/v0.4.21/meok_0.4.21_darwin_all.tar.gz"
    sha256 "a518c0b73efe69cba0bef897a4b3ae16e3b3aa11d49c41d2eff6901aaae81d8b"

    def install
      bin.install "meok"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoehwa/meok/releases/download/v0.4.21/meok_0.4.21_linux_arm64.tar.gz"
      sha256 "6f7a7f3806f62c4b9b19bd5fc48142c6d195b109b29f8a6f0be17f3605ecdbea"

      def install
        bin.install "meok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoehwa/meok/releases/download/v0.4.21/meok_0.4.21_linux_amd64.tar.gz"
      sha256 "35e64bf0c8c2c418cd1049165e3b795ff8d24ae6dcc20644824aad55f06ccb00"

      def install
        bin.install "meok"
      end
    end
  end
end
