# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Misc < Formula
  desc ""
  homepage "https://github.com/mindulle/misc"
  version "1.0.1"

  on_macos do
    url "https://github.com/mindulle/misc/releases/download/v1.0.1/misc_1.0.1_darwin_all.tar.gz"
    sha256 "763e86e2f87e40079a66108570f88f6db2618007e7cdca429787eddeb8881712"

    def install
      bin.install "misc"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mindulle/misc/releases/download/v1.0.1/misc_1.0.1_linux_arm64.tar.gz"
      sha256 "03dd000d7faca906803c87b6bfb3c450dcb6f4f50d38e704fdeef915b3afa9b8"

      def install
        bin.install "misc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mindulle/misc/releases/download/v1.0.1/misc_1.0.1_linux_amd64.tar.gz"
      sha256 "1b587dafe2511fb366d28dfd5afce71ae37bb5e7bb78388e2924f4dd1e000000"

      def install
        bin.install "misc"
      end
    end
  end
end
