# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orb < Formula
  desc ""
  homepage "https://github.com/Hwansul/orb"
  version "0.1.0"

  on_macos do
    url "https://github.com/Hwansul/orb/releases/download/v0.1.0/orb_0.1.0_darwin_all.tar.gz"
    sha256 "edcca9973bb5e14812f92602118e23405c8cae6e1dfab79704ca977f509bf995"

    def install
      bin.install "orb"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Hwansul/orb/releases/download/v0.1.0/orb_0.1.0_linux_arm64.tar.gz"
      sha256 "2d410638928ff8abe5488887843c457f6a1271d6a33d9e94e60fe63e2cdeb6fa"

      def install
        bin.install "orb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Hwansul/orb/releases/download/v0.1.0/orb_0.1.0_linux_amd64.tar.gz"
      sha256 "51ba10eabcc2d28d85ca72a8fd2c81851ded3b8c1d5b05bb5e41bf21780f188b"

      def install
        bin.install "orb"
      end
    end
  end
end
